DisNutz/GreenGroceries/blueprints/Login/routes.py
from flask import render_template, url_for, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user

from GreenGroceries.forms import UserLoginForm, UserSignupForm
from GreenGroceries.models import Farmer, Customer
from GreenGroceries.queries import get_user_by_user_name, insert_farmer, insert_customer
from GreenGroceries.utils.choices import UserTypeChoices

Login = Blueprint('Login', __name__)


@Login.route("/")
@Login.route("/home")
def home():
    return render_template('pages/home.html')


@Login.route("/about")
def about():
    return render_template('pages/about.html')


@Login.route("/style-guide")
def style_guide():
    return render_template('pages/style-guide.html')


@Login.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('Login.home'))
    form = UserLoginForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user = get_user_by_user_name(form.user_name.data)
            if user and user['password'] == form.password.data:
                login_user(user, remember=True)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('Login.home'))
    return render_template('pages/login.html', form=form)


@Login.route("/signup", methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('Login.home'))
    form = UserSignupForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            user_data = dict(full_name=form.full_name.data,
                             user_name=form.user_name.data,
                             password=form.password.data)
            if form.user_type.data == UserTypeChoices.values()[0]:
                farmer = Farmer(user_data)
                insert_farmer(farmer)
            elif form.user_type.data == UserTypeChoices.values()[1]:
                customer = Customer(form.data)
                insert_customer(customer)
            user = get_user_by_user_name(form.user_name.data)
            if user:
                login_user(user, remember=True)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('Login.home'))
    return render_template('pages/signup.html', form=form)


@Login.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('Login.login'))

DisNutz/GreenGroceries/blueprints/Produce/routes.py
from flask import render_template, request, Blueprint
from flask_login import login_required, current_user

from GreenGroceries.forms import FilterProduceForm, AddProduceForm, BuyProduceForm, RestockProduceForm
from GreenGroceries.models import Produce as ProduceModel, ProduceOrder
from GreenGroceries.queries import insert_produce, get_produce_by_pk, Sell, \
    insert_sell, get_all_produce_by_farmer, get_produce_by_filters, insert_produce_order, update_sell, \
    get_orders_by_customer_pk

Produce = Blueprint('Produce', __name__)


@Produce.route("/produce", methods=['GET', 'POST'])
def produce():
    form = FilterProduceForm()
    title = 'Our produce!'
    produce = []
    if request.method == 'POST':
        produce = get_produce_by_filters(category=request.form.get('category'),
                                         item=request.form.get('item'),
                                         variety=request.form.get('variety'),
                                         farmer_name=request.form.get('sold_by'),
                                         price=request.form.get('price'))
        title = f'Our {request.form.get("category")}!'
    return render_template('pages/produce.html', produce=produce, form=form, title=title)


@Produce.route("/add-produce", methods=['GET', 'POST'])
@login_required
def add_produce():
    form = AddProduceForm(data=dict(farmer_pk=current_user.pk))
    if request.method == 'POST':
        if form.validate_on_submit():
            produce_data = dict(
                category=form.category.data,
                item=form.item.data,
                variety=form.variety.data,
                unit=form.unit.data,
                price=form.price.data
            )
            produce = ProduceModel(produce_data)
            new_produce_pk = insert_produce(produce)
            sell = Sell(dict(farmer_pk=current_user.pk, produce_pk=new_produce_pk, available=True))
            insert_sell(sell)
    return render_template('pages/add-produce.html', form=form)


@Produce.route("/your-produce", methods=['GET', 'POST'])
@login_required
def your_produce():
    form = FilterProduceForm()
    produce = []
    if request.method == 'GET':
        produce = get_all_produce_by_farmer(current_user.pk)
    if request.method == 'POST':
        produce = get_produce_by_filters(category=request.form.get('category'),
                                         item=request.form.get('item'),
                                         variety=request.form.get('variety'),
                                         farmer_pk=current_user.pk)
    return render_template('pages/your-produce.html', form=form, produce=produce)


@Produce.route('/produce/buy/<pk>', methods=['GET', 'POST'])
@login_required
def buy_produce(pk):
    form = BuyProduceForm()
    produce = get_produce_by_pk(pk)
    if request.method == 'POST':
        if form.validate_on_submit():
            order = ProduceOrder(dict(produce_pk=produce.pk,
                                      farmer_pk=produce.farmer_pk,
                                      customer_pk=current_user.pk))
            insert_produce_order(order)
            update_sell(available=False,
                        produce_pk=produce.pk,
                        farmer_pk=produce.farmer_pk)
    return render_template('pages/buy-produce.html', form=form, produce=produce)


@Produce.route('/produce/restock/<pk>', methods=['GET', 'POST'])
@login_required
def restock_produce(pk):
    form = RestockProduceForm()
    produce = get_produce_by_pk(pk)
    if request.method == 'POST':
        if form.validate_on_submit():
            update_sell(available=True,
                        produce_pk=produce.pk,
                        farmer_pk=produce.farmer_pk)
    return render_template('pages/restock-produce.html', form=form, produce=produce)


@Produce.route('/produce/your-orders')
def your_orders():
    orders = get_orders_by_customer_pk(current_user.pk)
    return render_template('pages/your-orders.html', orders=orders)

DisNutz/GreenGroceries/templates/components/footer.html
<footer>
    <div>
        <span>© DIS Nutz</span>
        <a href="{{ url_for('Login.style_guide') }}">Style Guide</a>
        <a href="{{ url_for('Login.about') }}">About</a>
    </div>
</footer>

DisNutz/GreenGroceries/templates/components/macros.html
{% macro cta_button (class='') %}
    <a class="btn {{ class }}" href="{{ url_for('Produce.produce') }}">
        <span>
            <img src="{{ url_for('static', filename='images/icons/cart.svg') }}" alt="cart" class="icon">
            Start shopping
        </span>
    </a>
{% endmacro %}


{% macro form_errors (errors=[]) %}
    {% for error in errors %}
        <span class="text--red">{{ error }}</span>
    {% endfor %}
{% endmacro %}


{% macro select_field (name='', choices=[]) %}
    <select name="{{ name }}" id="{{ name }}" aria-label="{{ name }}">
        <option value=null selected disabled>Choose an option...</option>
        {% for choice in choices %}
            <option value="{{ choice[0] }}">{{ choice[1] }}</option>
        {% endfor %}
        {{ form.category.options }}
    </select>
{% endmacro %}


{% macro filter_produce_form (form=None, sold_by=True) %}
    <form method="POST">
        {{ form.hidden_tag() }}

        <div class="form--row">
            <div class="form-group">
                {{ form.category.label }}
                {{ form.category }}
            </div>

            <div class="form-group">
                {{ form.item.label }}
                {{ form.item }}
            </div>

            <div class="form-group">
                {{ form.variety.label }}
                {{ form.variety }}
            </div>
        </div>

        <div class="form--row">
            {% if sold_by %}
                <div class="form-group">
                    {{ form.sold_by.label }}
                    {{ form.sold_by }}
                </div>
            {% endif %}

            <div class="form-group">
                {{ form.price.label }}
                {{ form.price }}
            </div>

            {{ form.submit(class="btn") }}
            <a href="{{ url_for('Produce.produce') }}" class="btn">Clear filters</a>
        </div>
    </form>
{% endmacro %}


{% macro produce_card (product=None, show_checkout=True, show_restock=False, date=None) %}
    <div class="card">
        <div class="card__info">
            {% if date %}
                <p>Date: {{ date }}</p>
            {% endif %}
            <p>Category: {{ product.category|format_data }}</p>
            <p>Item: {{ product.item|format_data }}</p>
            <p>Variety: {{ product.variety|format_data }}</p>
            <p>Price: £{{ product.price }} / {{ product.unit }}</p>
            {% if not date %}
                <p>In stock: {{ product.available }}</p>
                <p>Sold by: {{ product.farmer_name }}</p>
            {% endif %}
        </div>

        <div class="card__action">
            {% if show_checkout %}
                {% if product.available %}
                    <a href="{{ url_for('Produce.buy_produce', pk=product.produce_pk) }}">Buy</a>
                {% endif %}
            {% else %}
                {% if show_restock %}
                    {% if not product.available %}
                        <a href="{{ url_for('Produce.restock_produce', pk=product.produce_pk) }}">Restock</a>
                    {% endif %}
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endmacro %}

DisNutz/GreenGroceries/templates/components/navbar.html
<nav>
    <div>
        <div class="links-wrapper">
            <a href="{{ url_for("Login.home") }}">Home</a>
            <a href="{{ url_for("Produce.produce") }}">All Produce</a>
            {% if current_user.is_authenticated %}
            <a href="{{ url_for("Produce.add_produce") }}">Add Produce</a>
            <a href="{{ url_for("Produce.your_produce") }}">Your Produce</a>
            <a href="{{ url_for("Produce.your_orders") }}">Your Orders</a>
            {% endif %}
        </div>

        <div class="links-wrapper">
            {% if current_user.is_authenticated %}
                <span class="text--gray">Logged in as: {{ current_user.user_name }}</span>
                <a href="{{ url_for("Login.logout") }}">Logout</a>
            {% else %}
                <a class="text--gray" href="{{ url_for("Login.signup") }}">Sign up</a>
                <a href="{{ url_for("Login.login") }}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>